In [1]:
import numpy as np
import pandas as pd

In [2]:
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [3]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [4]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [5]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [6]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

## Date

In [7]:
# Converting to datetime datatype
date['date'] = pd.to_datetime(date['date'])

In [8]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

In [11]:
date['date_year'] = date['date'].dt.year

date.sample(1)

          date  product_id  city_id  orders  date_year  date_month_no
582 2019-07-22        1031        0       1       2019              7

In [10]:
date['date_month_no'] = date['date'].dt.month

date.sample(1)

          date  product_id  city_id  orders  date_year  date_month_no
755 2019-07-07        4457       22      30       2019              7

In [12]:
date['date_month_name'] = date['date'].dt.month_name()

date.sample(1)

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name
332,2019-07-02,1467,22,63,2019,7,July

In [13]:
date['date_day'] = date['date'].dt.day

date.sample(1)

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day
285,2018-10-19,6619,4,1,2018,10,October,19

In [14]:
# day of week
date['date_dow'] = date['date'].dt.dayofweek

date.sample(1)

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_dow
194,2019-08-09,5,16,1,2019,8,August,9,4

In [16]:
# day of week - name

date['date_dow_name'] = date['date'].dt.day_name()

date.drop(columns=['product_id','city_id','orders']).sample()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name
886,2018-09-05,2018,9,September,5,2,Wednesday

In [17]:
# is weekend?

date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday', 'Saturday']), 1,0)

date.drop(columns=['product_id','city_id','orders']).sample()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend
804,2018-10-03,2018,10,October,3,2,Wednesday,0

In [19]:
date['quarter'] = date['date'].dt.quarter

date.drop(columns=['product_id','city_id','orders']).sample()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,quarter
3,2019-08-17,2019,8,August,17,5,Saturday,1,3

#### diff in days and time

In [20]:
import datetime

today = datetime.datetime.today()

today

datetime.datetime(2026, 3, 20, 16, 40, 49, 306099)

In [21]:
today - date['date']

0     2292 days 16:40:49.306099
1     2774 days 16:40:49.306099
2     2705 days 16:40:49.306099
3     2407 days 16:40:49.306099
4     2630 days 16:40:49.306099
                 ...
995   2720 days 16:40:49.306099
996   2661 days 16:40:49.306099
997   2509 days 16:40:49.306099
998   2574 days 16:40:49.306099
999   2348 days 16:40:49.306099
Name: date, Length: 1000, dtype: timedelta64[ns]

In [22]:
(today - date['date']).dt.days

0      2292
1      2774
2      2705
3      2407
4      2630
       ...
995    2720
996    2661
997    2509
998    2574
999    2348
Name: date, Length: 1000, dtype: int64

## time

In [25]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [26]:
# Converting to datetime datatype
time['date'] = pd.to_datetime(time['date'])

In [27]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [28]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.sample()

,date,msg,hour,min,sec
652,2014-08-31,ХУЛИГАНКА.ЖДУ ЗВОНКОВ ОТ ЗАПОРОЖАН...0500764910,0,0,0

In [30]:
time['time'] = time['date'].dt.time

time.sample()

,date,msg,hour,min,sec,time
501,2012-02-26 01:29:00,М.43 ИЩЕТ ЖЕНЩИНУ 40-55 ЛЕТ ДЛЯ ЖИЗНИ.ДНЕПР. 0...,1,29,0,01:29:00

In [31]:
today - time['date']

0     4478 days 15:50:49.306099
1     4342 days 17:00:49.306099
2     4828 days 16:19:49.306099
3     4130 days 16:09:49.306099
4     4527 days 17:29:49.306099
                 ...
995   5117 days 15:50:49.306099
996   4438 days 17:26:49.306099
997   4903 days 17:03:49.306099
998   5019 days 17:06:49.306099
999   4291 days 17:15:49.306099
Name: date, Length: 1000, dtype: timedelta64[ns]

In [32]:
# in seconds

(today - time['date'])/np.timedelta64(1,'s')

0      3.869562e+08
1      3.752100e+08
2      4.171980e+08
3      3.568902e+08
4      3.911958e+08
           ...
995    4.421658e+08
996    3.835060e+08
997    4.236806e+08
998    4.337032e+08
999    3.708045e+08
Name: date, Length: 1000, dtype: float64

In [33]:
# in minutes

(today - time['date'])/np.timedelta64(1,'m')

0      6.449271e+06
1      6.253501e+06
2      6.953300e+06
3      5.948170e+06
4      6.519930e+06
           ...
995    7.369431e+06
996    6.391767e+06
997    7.061344e+06
998    7.228387e+06
999    6.180076e+06
Name: date, Length: 1000, dtype: float64

In [34]:
# in hours

(today - time['date'])/np.timedelta64(1,'h')

0      107487.847029
1      104225.013696
2      115888.330363
3       99136.163696
4      108665.497029
           ...
995    122823.847029
996    106529.447029
997    117689.063696
998    120473.113696
999    103001.263696
Name: date, Length: 1000, dtype: float64